extensions = ("default", "pckgdep", "provxml", "resource", "uninstall",
    "manifest", "settingcontent-ms", "automaticdestinations-ms",
    "customdestinations-ms", "log1", "log2", "log3", "log4", "log5", "log6",
    "log7", "log8", "log9", "gm81", "tiger", "catproduct", "kdbx", "note",
    "crdownload", "vdoc", "lock", "game", "vbox", "nitf", "zargo", "safe",
    "vbox-extpack", "html", "ylib", "msproducer", "plsc", "qhcp", "maff",
    "szproj", "blend", "xmpz", "trash", "dired", "123dx", "ipsw", "email",
    "graffle", "evtx", "tocg", "bdmv", "xish", "vbox-prev", "azw2", "icfm",
    "ffivw", "pages", "azw1", "dtsi", "kext", "fsproj", "epub", "aspx", "3dmf",
    "jnlp", "trib", "yookoo", "dbfx", "mdmp", "atml", "flac", "saver",
    "4dindy", "vsdm", "policy", "fasta", "accdt", "mol2", "ingr", "contact",
    "dats", "bufr", "smclvl", "plist", "xisb", "vsdx", "hdmp", "wifi", "vmcz",
    "vala", "wireframe", "face", "rmvb", "vstx", "xmod", "vrml", "dylib",
    "sh3d", "workflow", "xlsb", "plantuml", "spin", "xlsx", "ccitt", "plsk",
    "cpmz", "mpkg", "vlogo", "olsr", "fstick", "jbig", "chml", "tpoly",
    "webloc", "ssif", "ecmt", "docx", "yaml", "mediawiki", "lisp", "escsch",
    "mppz", "scpt", "mpeg", "cats", "3dsx", "scptd", "grdnt", "fb2k",
    "gameproj", "swift", "vbproj", "djvu", "xlsm", "blob", "mobi", "mlraw",
    "adicht", "ampl", "sdts", "psppalette", "lasso", "midi", "aifc",
    "steamstart", "elfo", "ipynb", "iv-vrml", "soar", "spiff", "sldasm",
    "weboogl", "class", "xisf", "sldprt", "numbers", "pipe", "php3", "vsto",
    "rbxl", "tmy2", "flame", "accda", "coffee", "icfe", "odif", "dicom",
    "udiwww", "xlbl", "sha1", "pack", "xspf", "tddd", "ftxt", "unif", "part",
    "vicar", "vmdk", "text", "pncl", "runz", "jpeg", "vstm", "vsqx", "acmb",
    "escpcb", "m2ts", "topc", "fweb", "film", "iptc", "msdl", "iges", "slddrw",
    "dvdproj", "package", "olk14contact", "file", "accdu", "psm1", "schematic",
    "opus", "viff", "jasc", "lang", "eossa", "pblib", "t2flow", "jfif",
    "manager", "wiki", "schdoc", "fsim", "pkpass", "amlx", "uoml", "bmpw",
    "cmrl", "kodu", "m3u8", "hcgs", "dfti", "qrmx", "sndb", "genbank", "grads",
    "naplps", "term", "irtr", "ppsx", "pseg", "dotx", "gmod", "scala",
    "fb2k-component", "vinf", "emaker", "proj", "dbpro", "accft", "sqlite",
    "info", "artx", "torrent", "vssx", "grasp", "rbxm", "miniusf", "aiff",
    "php4", "indd", "kbasic", "rdata", "xosm", "isma", "love", "java", "stuff",
    "onepkg", "uzed", "bpoly", "kfdk", "accdb", "miff", "anim", "wsrc", "objf",
    "hpgl", "qtvr", "oeaccount", "json", "msdvd", "netcdf", "balance",
    "desklink", "xrm-ms", "greenfoot", "hppcl", "adef", "poly", "shar", "font",
    "smpl", "sats", "catdrawing", "sdml", "pict", "ptped", "jsonld", "tiff",
    "rtfd", "themepack", "neis", "grft", "pptx", "cweb", "tria", "attf",
    "sctor", "trif", "enff", "properties", "mime", "rhistory", "msqm", "vssm",
    "catpart", "desktop", "accde", "cals", "docm", "asmx", "proto", "ecms",
    "plugin", "irrmesh", "ply2", "quox", "beam", "par2", "clpi", "vcls",
    "theme", "bdef", "fits", "wmdb", "adson", "clprj", "grib", "ibro", "saif", 
    "3gp_128x96", "3gp2", "3gpp", "3gpp2", "3ivx", "arcut", "asdvdcrtproj", 
    "avchd", "awlive", "badongo", "bdav", "bdt2", "bdt3", "bdtp", "camproj", 
    "camrec", "camthtr", "camv", "cavs", "cine", "cmmp", "cmmtpl", "cmproj", 
    "cmrec", "cpvc", "crec", "daproj", "dash", "db2mov", "demo", "demo4", 
    "dfxp", "divx", "djanimations", "dmsd", "dmsd3d", "dmskm", "dmsm", "dmss", 
    "doink-gs", "dscf", "dtcp-ip", "dv-avi", "dvddata", "dvdmedia", "dvdrip", 
    "dvr-ms", "dvsd", "encm", "etrg", "eztv", "fcproject", "fcpxml", 
    "flexolibrary", "fli_", "flic", "flux", "flvat", "ftvx", "g64x", "gdwx", 
    "gifv", "h.263", "h260", "h261", "h263", "h-263", "h263+", "h264", "h265", 
    "hbox", "hdmov", "hevc", "hm10", "imovieproj", "imovieproject", "imovietrailer", 
    "ircp", "ismv", "izzy", "kava", "lrec", "lsproj", "m1pg", "mepx", "mjp2", 
    "mjpeg", "m-jpeg", "mjpg", "mk3d", "mkv3D", "ml20", "moff", "moov", "movie", 
    "mp21", "mp2v", "mp41", "mp4v", "mpcpl", "mpeg1", "mpeg2", "mpeg4", "mpegps", 
    "mpg2", "mpg4", "mpgv", "mpgx", "mpv2", "mpv4", "mts1", "mv85", "mv93", "mv95", 
    "ncor", "ncorx", "nvavi", "olproj", "otrkey", "pgmx", "pproj", "prel", "prproj", 
    "qcif", "rargb", "ratDVD", "ravi", "rcproject", "rcrec", "rcut", "rec_part0", 
    "rec_part1", "rec_part2", "rec_part3", "rtsl", "rtsp", "rvid", "s4ud", "sbsc", 
    "sbst", "sdr2", "sfvidcap", "sgvx", "smpg", "snapfireshow", "splash", "strg", 
    "svcd", "tda3mt", "tdt2", "theater", "tivo", "trec", "tridefmovie", "tscproj", 
    "tstream", "tvml", "tvod", "tx3g", "uvcab", "uvnts", "uvseg", "v264", "vcpf", 
    "vcprj", "vep4", "vghd", "video", "viewlet", "vivo", "vlab", "vmlf", "vp10", 
    "vprj", "vproj", "webm", "wfsp", "wlmp", "wmmp", "wmv3", "wsve", "xavc", "xlmv", 
    "xtodvd", "xvid", "xwmv", "yify", "2sflib", "8svx", "acid", "addoc", "adts", 
    "aifr", "akai", "alac", "alaw", "amsproj", "amxd", "apex", "architect", "aria", 
    "ariax", "arpx8", "asnd", "atak", "atrac", "audionote", "aupreset", "band", 
    "bmtp", "br25", "br27", "br28", "br29", "br31", "br32", "br48", "brsar", "brstm", 
    "btab", "camelsounds", "cdda", "cdfs", "celp", "cvsd", "dewf", "djmusic", 
    "dmkit", "dmpatch", "dmptrn", "dmsa", "dmse", "dpdoc", "dtshd", "e2ev", "eac3", 
    "elastik", "eragesoundset", "eseq", "evrc", "fc14", "fred", "fspro", "ftmx", 
    "g721", "g723", "G723-3", "g726", "g726-2", "g726-3", "glue", "gpbank", "h2song", 
    "hcom", "i3pack", "ima4", "itls", "kris", "logic", "logicx", "loop", "lpcm", 
    "lthmb", "ma2.mmf", "maud", "minibank", "minigsf", "mkII", "mmpz", "mogg", "mp3a", 
    "mp3g", "mp3pro", "mp3url", "mp4a", "mp4b", "mpdp", "mpega", "mpg3", "mpga", 
    "mptm", "mscx", "mscz", "mus  mus", "mus10", "musx", "mwand", "mwav", "mxc2", 
    "mxmf", "nabs", "narrative", "nbkt", "nfd_audio", "nfm8", "ngrr", "niff", "nist", 
    "nmsv", "nsfe", "nsla", "nsmp", "ocdf", "omfi", "paal", "pch2", "peak", "plst", 
    "ppcx", "ps16", "psf2", "psflib", "psmm", "ptcop", "pttune", "ptxt", "puma", 
    "record", "repatch", "rf64", "rgtrack", "ring", "rockwell", "rtttl", "sabl", 
    "sabs", "sc68", "scs11", "sd2f", "sdat", "sdii", "sdir", "sesx", "sfark", "sfil", 
    "smaf", "smfmf", "smpx", "sndh", "song", "sonic", "ssdl", "stem", "stem.mp4", 
    "stmp", "ulaw", "vdjsample", "vox-6k", "vox-8k", "voxal", "wand", "waptt", "wavc", 
    "wave", "wave64", "weba", "wproj", "wusiksnd", "xpak", "xrns", "xsml", "xvag", 
    "xwma", "ytif", "00_jpg_srb", "00_jpg_srz", "00_png_srz", "2bp ", "600x", 
    "aas+A897", "acbm", "accountpicture-ms", "acorn", "adex", "agif", "ahrp", 
    "alias", "apalbum", "apng", "artwork", "avif", "bitmap", "bmp ", "bmp_", 
    "bmp24", "bmpp", "brush", "btpc", "ccrf", "cdr3", "cdr4", "cdr5", "cdr6", "cdrw", 
    "cdrzip", "cimg", "clgx", "clip", "cmyk", "cmyka", "core", "cpbitmap", "cube", 
    "dcim", "design", "dicm", "dpx ", "drw2", "drw5", "ebmp", "eidi", "eosat", "exif", 
    "fac ", "ffpx", "fido", "flif", "fpix", "fpos", "fppx", "frdat", "gif_160x120", 
    "gif~c200", "gif89a", "giff", "gmbck", "graf", "grob", "ham6", "ham8", "hdri", 
    "hdru", "heic", "heif", "hips", "huge", "ico_", "icon", "idrc", "idrw", "ilbm", 
    "image", "inta", "ioca", "iraf", "itc2", "ivue", "iw44", "jascproject", "jbig2", 
    "jfif-tbnl", "jiff", "jp2_", "jpeg_128x96", "jpeg_160x120", "jpeg_170x220", 
    "jpg_108x192", "jpg_120х178", "jpg_128x128", "jpg_128x160", "jpg_128x96", 
    "jpg_160x120", "jpg_160x128", "jpg_170x128", "jpg_170x220", "jpg_220x176", 
    "jpg_240x320", "jpg_320x240", "jpg_320x320", "jpg_480x320", "jpg_512x512", 
    "jpg_56x42", "jpg_t", "jpg_thumb", "jpg2", "jpg3", "jpge", "jpg-large", "jpg-original", 
    "jpig", "jtif", "kodak", "landsat", "lansat", "ljpg", "macp", "mask", "mbfavs", 
    "mbfs", "mbfx", "mcpp", "mitsu", "mono", "mpnt", "mraw", "mtiff", "ncsa", "ndpi", 
    "ndpr", "oplc", "paint", "pamp", "pano", "pattern", "pbmb", "pcx_", "pgal", "pgma", 
    "pgmb", "pi[1-6]", "picnc", "picon", "pict1", "pict2", "pictclipping", "pictor", 
    "pixar", "pixelpaint", "pjpeg", "pjpg", "png24", "png32", "png8", "png-large", 
    "pngt", "pntg", "psdt", "psdx", "pspimage", "psxprj", "ptif", "puzz", "pyxel", 
    "rast", "rawraw", "rgb8", "rgba", "rgbn", "riff", "rimg", "rpgm", "sai2", "sbig", 
    "scan", "sdpx", "sdwx", "sedprj", "sham", "sixel", "snag", "snap", "spot", "sprite", 
    "stn=", "sumo", "swgr", "synu", "texture", "thmb", "thumb", "tile", "tpic", "ugoira", 
    "uyvy", "vclip", "vrphoto", "wbmp", "webp", "ximg", "xpng", "x-png", "xyzi", "craw", 
    "gray", "grey", "ycbcra", "_docx", "_pdf", "ab65", "abicollab", "accdp", "acrypt", 
    "activitydiagram", "ados", "adox", "adpr", "aepx", "aggr", "agldei", "aglsl", 
    "aidf", "alb3", "alb4", "alb5", "ald5", "alt3", "alt5", "alt6", "amsm", "amst", 
    "ansr", "avery", "awwp", "bamboopaper", "bbprojectd", "bcard", "bdoc", "bean", 
    "bibtex", "bina", "bizdocument", "bmpr", "bobo", "book", "booktemplate", "bpmc", 
    "burn", "burntheme", "bzabw", "c1dx", "cadoc", "calca", "camm", "capt", "cddz", 
    "cdml", "cdmm", "cdmt", "cdmtz", "cdmz", "cipo", "cl2lyt", "cl2tpl", "clarify", 
    "clbx", "clkd", "comicdoc", "comiclife", "compositiontemplate", "converterx", "cpdt", 
    "cptl", "cptx", "crev", "crtr", "ctxt", "cwks", "cwwp", "ddif", "deproj", "dgpd", 
    "dgrh", "disco", "dk@p", "dmmx", "dmpr", "dmtemplate", "doc#", "dochtml", "docmhtml", 
    "docs", "docset", "doct", "docxml", "dothtml", "dotm", "drmx", "drmz", "dwdoc", 
    "dwlibrary", "dxstudio", "easmx", "ebkproj", "eddx", "edml", "edoc", "efax", "emcmf", 
    "emcx", "emlx", "enex", "enyd", "epdf", "eprtx", "etng", "etnt", "ezpx", "fadein", 
    "fbok", "fcdt", "fdxt", "ffdata", "fire", "fmap", "fmp3", "fodp", "fodt", "form", 
    "fpage", "frdoc", "freeway", "fsform", "fsif", "ftil", "ftlx", "ftmt", "ftpl", 
    "fwrt", "fwtb", "fwtemplate", "fwtemplateb", "gca3", "gca4", "gca4base", "gevl", 
    "gexf", "gif2", "gnote", "gofin", "grade", "help", "hmxp", "hmxz", "htz5", "hwpml", 
    "hype", "ibatemplate", "ibcd", "icalevent", "icaltodo", "icma", "icml", "icmt", 
    "icst", "idap", "idml", "ildoc", "imscc", "imsp", "imtx", "incp", "inct", "indb", 
    "indn", "indt", "infopathxml", "inld", "inrs", "insx", "isale", "isaletemplate", 
    "isdoc", "isdocx", "ish1", "ish3", "ispx", "itmz", "iwprj", "iwtpl", "iwzip", 
    "jlqm", "jtdc", "keynote", "key-tef", "klip", "laba", "latex", "layoutdesigner", 
    "lgpl", "logonxp", "lpdf", "lucy", "maca", "manu", "marc", "markdn", "mars", 
    "mass", "mbbk", "mcbn", "mcdx", "mcmac", "mcsp", "mdbhtml", "mdhtml", "mell", 
    "mellel", "mgourmet", "mgourmet3", "mindnode", "miradi", "mjbooktemplate", "mjdoc", 
    "mmap", "mmas", "mmat", "mmmp", "mmpr", "mmsw", "moml", "montage", "mpls", "mpp_", 
    "mppx", "mpwd", "mshc", "msor", "mswd", "muse", "mvtx", "mwii", "mwpd", 
    "mwpp", "mwpr", "mxfd", "nbib", "nclk", "ngloss", "notebook", "npdf",
    "nwcp", "nx^d", "nx__", "ocdc", "odccubefile", "odt#", "ole2", "oplx", 
    "opsx", "opxs", "opxt", "oxps", "p2bp", "pages-tef", "pbix", "pbproj", 
    "pdf_", "pdf_tsid", "pdfa", "pdfe", "pdfua", "pdfvt", "pdfx", "pdfxml", 
    "pfsx", "pjtf", "plan", "pltx", "pmatrix", "pool", "pothtml", "potx", 
    "ppdf", "ppnt", "ppot", "ppsm", "ppt3", "ppta", "ppthtml", "pptm", "pptmhtml", 
    "pptt", "pptv", "pptxml", "prnx", "pro4", "pro4dvd", "pro5", "pro5dvd", 
    "pro5plx", "pro5x", "project", "proqc", "prs1", "prs2", "prt1", "prt2", 
    "psmd", "psproj", "pubf", "pubhtml", "publication", "pubmhtml", "pworks", 
    "pzfx", "qhtm", "qprj", "quiz", "quiztemplate", "raml", "rdlx", "rels", 
    "rise", "roff", "rolf", "rptr", "rptx", "rrpa", "rtab", "rtdf", "rtf_", 
    "s6bn", "s8bn", "sbpf", "scriv", "scrivx", "sdbn", "sdxml", "seek", 
    "sevz", "sgml", "sheet", "show", "simp", "sites", "sld3", "sld8", "slds", 
    "smdf", "smmx", "spdesignshtm", "spdf", "sprz", "spub", "ssiw", "sskd", 
    "stmx", "stpl", "stplz", "suml", "svdl", "svslide", "swdoc", "sxml", 
    "sysml", "t3001", "tabula-doc", "taxform", "tbkx", "tceltx", "tdoc", 
    "texi", "tmvt", "tnsp", "totalslayout", "tracwiki", "ttax", "twbx", 
    "twdx", "twiki", "txss", "txtrpt", "ulys", "updf", "vcal", "vcproj", 
    "vdproj", "voprefs", "vthought", "w6bn", "w8bn", "w8tn", "wdbn", "wdcd", 
    "wdoc", "webdoc", "webtemplate", "whtt", "wizhtml", "word", "wp42", "wp50", 
    "wpc2", "wpd0", "wpd1", "wpd2", "wpd3", "wpost", "wpostx", "wrlk", "wtbn", 
    "wwcx", "wxmx", "xbrl", "xdoc", "xfdf", "xfdl", "xgmml", "xlc_", "xlc3", 
    "xlc4", "xline", "xlist", "xlshtml", "xlst", "xlthtml", "xmct", "xmdx", 
    "xmind", "xmls", "xmltv", "xmmas", "xmmat", "xmmmp", "xpr3", "xprj", 
    "xpwe", "xtps", "xy4v", "xzfx", "xzip", "ybhtm", "zave", "zrtf", "adiumhtmllog", 
    "adiumlog", "android", "annot", "ansi", "application", "aprj", "arff", 
    "artask", "ascii", "assoc", "bbxt", "big5", "bpdx", "bsdl", "cascii", 
    "charset", "chord", "clipping", "clix", "cm0013", "conf", "crash", "crwl", 
    "csassembly", "csmanifest", "dectest", "desc", "diskdefines", "dsml", 
    "ecsv", "emulecollection", "extra", "first", "full", "gthr", "guide", 
    "html5", "htmls", "id31", "id32", "igtx", "inuse", "kahl", "label", 
    "linux", "linx", "lxfml", "markdown", "mathml", "maxfr", "mdle", "mdown", 
    "mdtext", "mdtxt", "mdwn", "mkdn", "modd", "mpsub", "mtxt", "nmbd", "nokogiri", 
    "notes", "npdt", "nwctxt", "oogl", "openbsd", "opml", "panic", "rbdf", 
    "readme", "report", "resp", "rest", "sami", "sdnf", "sha512", "skcard", 
    "smali", "soap", "soundscript", "spec", "strings", "tdump", "textclipping", 
    "textile", "tmprtf", "tnef", "ttbl", "ttpl", "ttxt", "uhtml", "unauth", 
    "user", "utf8", "utxt", "vers", "vhdl", "vsmproj", "vxml", "xhtm", 
    "xlog", "xslt", "zanebug", "_xls", "awss", "csvx", "cwss", "excel", 
    "faff", "fods", "nmbtemplate", "numbers-tef", "siag", "silk", "sls3", 
    "sls4", "sls5", "sls8", "swss", "sxls", "sxlsx", "sylk", "valu", "xcel", 
    "xlmx", "xls_", "xls3", "xls4", "xls5", "xls8", "xlsmhtml", "xlsxe", 
    "xltm", "xltx", "xlw_", "xlw3", "xlw4", "xlw5", "xlxml", "xmap", "xmlx", 
    "xslb", "accdc", "accdr", "crtx", "laccdb", "potm", "ppam", "rpmsg", "sldm", 
    "sldx", "thmx", "xlam", "emix", "ldif", "list", "mail", "maildb", 
    "mailhost", "mbox", "mmdf", "mozeml", "olk14msgattach", "outlook97", 
    "schd", "vcard", "vrge08contact", "vrge08event", "vrge08group", "vrge08message", 
    "vrge08note", "wdseml", "_eml", "a5wcmp", "ahtm", "argo", "ascx", "ashx", 
    "asis", "atom", "bimd", "binarycookies", "bkmk", "bookexport", "bson", "btapp", 
    "caps", "cert", "cfml", "chtml", "cook", "cscpkt", "cshtml", "css1", 
    "dbmg", "dbnx", "dctmp", "defaultsite", "dime", "discomap", 
    "disposition-notification", "dita", "download", "dpsml", "dropbox", 
    "ed2k", "epibrw", "esproj", "fdml", "feed-ms", "feedsdb-ms", "fhtml", 
    "folder.metadata", "fpsml", "fpweb", "fpxml", "gdoc", "gdocx", "gdraw", 
    "getright", "gform", "gim ", "glink", "gscript", "gsheet", "gslides", "gtable", 
    "handlebars", "hathdl", "hdml", "hhtml", "hsql", "htm~", "htms", "ihtml", "ilht", 
    "imap", "imported", "jccfg3", "jhtml", "jsobj", "jspa", "jspx", "jsxbin", 
    "kismac", "ktspack", "lavs", "ldap", "ldmt", "link", "lwac", "lwbm", "lwtt", 
    "magnet", "mapx", "meta4", "metalink", "mhtm", "mhtml", "mman", "moss", 
    "msie", "mspx", "msrcincident", "ms-tnef", "mtml", "murl", "mxml", "newsloc", 
    "nsconfig", "obml", "obml15", "obml16", "ognc", "opdownload", "page", "page.security", 
    "pando", "partial", "phar", "php5", "phps", "phtm", "phtml", "pixate", "psml", 
    "pubkr", "rhtml", "rwsw", "saveddeck", "securedownload", "sflb", "shtm", 
    "shtml", "sitemap", "smil", "spdesignopen", "spdesignsitemap", "spml", "ssage", 
    "stml", "swf2", "swfl", "tpsml", "ttml", "tvpi", "tvvi", "upload", "uris", 
    "url_", "urls", "vmsg", "vsdisco", "wbxml", "wdgt", "webarchivexml", 
    "webbookmark", "webhistory", "webintents", "webpnp", "webpublishhistory", 
    "website", "webtest", "wmlc", "wmlsc", "xbap", "xhtml", "xrds", "xtml", 
    "xweb3asax", "xweb3htm", "xweb4shtml", "yaws", "zhtml", "zpweb", "7z.001", 
    "7z.002", "7z.003", "7z.004", "7z.005", "7z.006", "7z.007", "7z.008", "7z.009", 
    "7z.010", "7z.011", "7z.012", "7z.013", "7z.014", "7z.015", "7z.016", "7z.017", 
    "7z.018", "7z.019", "7z.020", "7z.021", "7z.023", "7z.025", "7z.027", "7z.028", 
    "7z.029", "7z.030", "7z.031", "7z.032", "7z.033", "7z.034", "7z.035", "7z.036", 
    "7z.037", "7z.039", "7zip", "7-zip", "abbu", "acd-zip", "adsm", "afzplug", 
    "antifrag", "apple", "appv", "appxbundle", "arch00", "archiver", "as4a", 
    "asec", "atla", "bulk", "bulk-003", "bzip", "bzip2", "carb", "cdoc", "chunk001", 
    "compress", "cpgz", "cpio", "ctit", "czar", "czip", "darc", "devpackage", 
    "devpak", "diagcab", "diagpkg", "djprojects", "dtsx", "dxtheme", "eappx", 
    "enc4", "enfpack", "enlx", "enpack", "fcarch", "fcxe", "flmod", "fpkg", 
    "framework", "fuzz", "gfar", "gnutar", "gtar", "gzip", "hbc2", "hstx", 
    "htmlz", "imoviemobile", "itmsp", "jar.pack", "lime", "lzma", "lzma86", 
    "lzop", "macbin", "mdzip", "mmip", "mvdx", "mzip", "nsarc", "ntfs", "nuget", 
    "nupkg", "nwcab", "obpack", "pack.gz", "pact", "paq6", "paq7", "paq8o", 
    "part00000", "part1.exe", "part1.rar", "part10.rar", "part11.rar", 
    "part2.rar", "part3.rar", "part4.rar", "part5.rar", "part6.rar", 
    "part7.rar", "part8.rar", "part9.rar", "pkg_", "propdesc", "pwzip", 
    "pzip", "quad", "rar1", "rar5", "rarx", "res11", "rgss2a", "seg1", 
    "sfds", "sfpack", "sisx", "sit!", "sit5", "sitd", "sithqx", "sitx", 
    "smilebox", "snagitstamps", "snappy", "snoop", "solitairetheme8", 
    "soundpack", "spar", "spkg", "split", "sqfs", "srep", "szdd", "tar.gz", 
    "tar.xz", "tar.z", "taraa", "tardist", "tar-gz", "tar-z", "tbz2", "texturepack", 
    "tzip", "ufdr", "ufs.uzip", "unitypackage", "uzip", "vol1.egg", "vol5.egg", 
    "vol8.egg", "volarchive", "vsix", "waff", "wapt", "warc", "wbpz", 
    "webarchive", "wlpk", "xdelta", "xmcdz", "yaz0", "yrcbkm", "zabw", 
    "zfsendtotarget", "zip2", "zipfs", "zipx", "zlib", "zpaq", "zsplit", 
    "zx01", "zx02", "$er $er", "abcdmr", "acad", "accdw", "asdb", "awbs", 
    "awdb", "btree", "celtx", "changedb", "changedb-journal", "cidb", "cwdb", 
    "daschema", "db2p", "db-journal", "dblib", "dcmd", "devx", "dhcd", 
    "dsdb", "dstf", "ecfg", "erbsql", "event", "f+db", "ffs_db", "fmdb", 
    "fmk4", "fmp12", "fmpr", "fmpsl", "ftch", "hkdb", "htri", "idb2", "iflv", 
    "indx", "ipdb", "isam", "itld", "joml", "kexi", "kpdx", "kseqs", "lutx", 
    "marshal", "mcdb", "mcsv", "mdbx", "mgdatabase", "mshdb", "mshi", "nlpe", 
    "nope", "nppe", "nspe", "nwdb", "od4-9", "oedb", "olk14dbheader", "otlb", 
    "pdbx", "prjx", "psafe3", "pwbk", "qbquery", "rgdb", "rsdb", "s2db", 
    "s3db", "sidx", "slife", "spentry", "sqlite2", "sqlite3", "sqlitedb", 
    "ssmssqlproj", "swdb", "syncdb-journal", "synciddb-journal", "teacher", 
    "thumbindex", "thumbsdb", "tmdb", "totalsdb", "totalssyncdb", "vdb3", "vpdb", 
    "wcat", "xaiml", "zodb", "arcinfo", "asrp", "bilw", "bpwx", "cadrg", "cdem", 
    "cgmap", "c-map", "csar", "cshp", "cwms", "dgdat", "ebmd", "elev", "freelist", 
    "freshcontact", "freshroute", "gdbtable", "gdbtablx", "geodatabase-shm", 
    "geodatabase-wal", "geojson", "gmap", "gprmc", "gprx", "gvsp", "hmap", "jgwx", 
    "jpgw", "kmtf", "lasx", "maplib", "mglr", "mglt", "mglw", "mpvf", "msys", 
    "mtkt", "navionics", "navmap", "nmap", "nmea", "nmgf", "owfs", "ozf2", "ozfx3", 
    "pgwx", "pkinfo", "pngw", "postal", "pwdef", "qgis", "rmap", "roadtrip", "rsrc", 
    "rtkt", "rtmap", "sdlic", "sosi", "spdb", "spud", "style", "tdmb", "tfrd", "tfwx", 
    "tifw", "ttkgp", "ttpkg", "upoi", "vmap", "wgom", "zlas", "_ipod_control", "_vti_bin", 
    "1092", "3_dpo", "access", "acct", "adups", "apdisk", "apple_partition_map", 
    "appledouble", "aslquery", "atahd", "bada", "bash_history", "bash_profile", "bbfw", 
    "bootefisignature", "bridgesupport", "bsdiff", "cachedump", "cdev", "colorpicker", 
    "component", "components", "crmlog", "ctfsys", "dat_tureg_old", "dbfseventsd", 
    "devicemanifest-ms", "dll_1029", "documentrevisions-v100", "ds_store", "dump", 
    "efires", "equiv", "exopc", "ext2", "ext4", "failurerequests", "fgdump-log", 
    "folder", "fseventsd", "fstab", "gadget", "group", "hpfs", "hsancillary", "ia64", 
    "icap", "identifier", "idx_dll", "im4p", "install_backup", "installhelper", 
    "ioplist", "irix6", "iswp", "jnilib", "journal_info_block", "kdmp", "localized", 
    "location", "lproj", "macs", "mapimail", "marker", "mdimporter", "migtable", 
    "mkext", "mojito", "monitorpanel", "mps_", "msdm", "muimanifest", "mydocs", 
    "n90ap", "ndrv", "nkey", "not_terminated", "novs", "osax", "osinstallmessages", 
    "payload", "prefpane", "profile", "qfilter", "qlgenerator", "quicktimecomponents", 
    "regtrans-ms", "restorelist", "riscos", "savedsearch", "scap", "scexe", "scsi", 
    "sdev", "searchindexcache", "seed", "service", "sfcache", "shlb", "shsh", 
    "sparc", "spreporter", "srec", "sucatalog", "supported", "system", "trx_dll", 
    "vmlt", "xdsl", "$efs", "___fpe", "1pif", "abcd", "acsm", "adoc", "aepkey", 
    "aes256", "aexpk", "afs3", "agilekeychain", "appt", "auth", "awsec", 
    "base64", "bexpk", "bioexcess", "bmpenx", "btoa", "cfog", "crpt", "crypt", 
    "crypt10", "crypt11", "crypt12", "crypt5", "crypt6", "crypt7", "crypt8", 
    "crypt9", "crypted", "cryptomite", "cryptra", "db.crypt5", "db.crypt7", 
    "db.crypt8", "devicesalt", "doce", "docenx", "docl", "docxenx", "docxl", 
    "dotmenx", "dotxenx", "edat", "egisenc", "egisenx", "embp", "eslock", "etxt", 
    "exportedfavorites", "fcfe", "filelock", "flka", "flkb", "flkw", "flwa", 
    "fpenc", "gifenx", "hid2", "htmlenx", "img3", "ivex", "jcrypt", "jmce", 
    "jmck", "jmcp", "jmcr", "jmcx", "jpegenx", "jpegx", "jpg_encrypted", 
    "jpgenx", "jpgx", "keychain", "leotmi", "lock3", "mbz5", "mcat", "mcrp", 
    "menc", "mhtenx", "mhtmlenx", "migitallock", "mkey", "mkeyb", "mpqe", 
    "mxls", "ontx", "opef", "pandora", "passwordwallet4", "pcxm", "pdfenx", 
    "pdfl", "pkcs12", "pkey", "pnne", "potmenx", "pp7m", "ppenc", "ppsenx", 
    "ppsxenx", "ppte", "pptenx", "pptl", "pptxenx", "prvkr", "pswx", "raes", 
    "rarenx", "rpgmvm", "rpgmvo", "rpgmvp", "rsdf", "SafeText", "sccef", "scke", 
    "sdoc", "sdsk", "sdtid", "secure", "sign", "signed", "sjpg", "smbp", "smht", 
    "sppt", "spsx", "stxt", "switch", "tifenx", "txtenx", "ueaf", "ueed", 
    "uenc", "v11pf", "vdata", "viivo", "vmdf", "walletx", "xcon", "xlamenx", 
    "xlse", "xlsenx", "xlsl", "xlsxenx", "xlsxl", "xtea", "y8pd", "yenc", "zipenx")


print (*('"{}"'.format(item) for item in sorted(extensions)), sep=", ")